### ISSUE TITLE
lunch.bat不更新

### ISSUE THREAD

**Issue by NoobChengXY** [CubeWhy/LunarClient-CN#10]
还是我
我在.cubewhy\lunarcn\config.json “jre”中放置了jdk17的路径，导致Lunar启动失败。据排查，lunch.bat并没有对config中的内容进行更新，在Lunar Client CN.exe中的表现为启动失败。值得注意的是，这个启动失败在Lunar客户端启动成功时也会出现。

我的推断：
在启动时，启动器创建了一个进程用于启动jar，但被taskkill了，导致每次启动都会出现
在taskkill前，会截取启动器的启动命令，放于lunch.bat，但在修改lunch.bat时出现了读取错误/权限不足/修改失败等问题，导致这个进程被提前终止，主进程检测到了，于是弹出启动失败的提示。

**Comment by CubeWhy** [comment]
任何情况启动器都会提示报错
而且jre参数要填java可执行文件的目录，配置正确之后才会生成launch.bat

**Comment by CubeWhy** [comment]
> 还是我 我在.cubewhy\lunarcn\config.json “jre”中放置了jdk17的路径，导致Lunar启动失败。据排查，lunch.bat并没有对config中的内容进行更新，在Lunar Client CN.exe中的表现为启动失败。值得注意的是，这个启动失败在Lunar客户端启动成功时也会出现。
> 
> 我的推断： 在启动时，启动器创建了一个进程用于启动jar，但被taskkill了，导致每次启动都会出现 在taskkill前，会截取启动器的启动命令，放于lunch.bat，但在修改lunch.bat时出现了读取错误/权限不足/修改失败等问题，导致这个进程被提前终止，主进程检测到了，于是弹出启动失败的提示。

而且并没有taskkill，你可以查看源代码，LunarClient CN的启动参数是`java -jar LunarCn.jar <原来的Lunar启动参数>`

并不是你说的启动之后捕获启动参数然后进行taskkill的

**Comment by NoobChengXY** [comment]
我正确填写了jre，并用双引号括起，会不会是在写入时没加双引号呢？

**Comment by CubeWhy** [comment]
\ (右斜线)需要替换为 \\ (两个右斜线)，否则会被转义，这个在README写了
