### ISSUE TITLE
[帮助页面] Overrides 实际作用

### ISSUE THREAD

**Issue by PlayMcBKuwu** [CubeWhy/LunarClient-CN#8]
**由于谷歌娘又在生草了，这里以 LowIQ 也能听懂的方式说一遍 Overrides 的实际作用。**
### *~~**CubeWhy 主播你听我狡辩这个 Issue 真的不是提问题的所以别急着关了**~~*
# 杰哥，这是什么啊？怎么用啊？
- 在美丽的 `%USER_PROFILE%/.lunarclient/offline/multiver/overrides/` 目录下，可以放自己的 `Mod`。  
- 理论上应该要在版本里选 Forge 选项，但是说了可以加 `Forge_v1_8.jar` 是不是意味着可以手动给某些版本安装 Forge？  
- 放进去的 Mod 格式应该是：`Mod 名称`+`_`+`v1_`+`Minecraft 版本号`+`.jar`，像是 `ReplayMod_v1_8.jar` 就是一个很好的例子

**Comment by CubeWhy** [comment]
感谢，已加入帮助页面
