### ISSUE TITLE
关于.cubewhy目录的问题

### ISSUE THREAD

**Issue by NoobChengXY** [CubeWhy/LunarClient-CN#9]
在Windows中，.cubewhy只会在不存在时创建目录及配置文件和启动脚本，且存在时不会更新和获取。
具体现象：
1. 当更改配置文件时，并不会读取
2. 当.cubewhy目录存在时，不会更改启动脚本

我已在多台电脑中尝试，都是这样，希望尽快修复！

**Comment by CubeWhy** [comment]
没明白你在说啥，那个文件夹是配置文件文件夹

**Comment by NoobChengXY** [comment]
对呀，就是配置文件夹

**Comment by NoobChengXY** [comment]
他不读取配置文件

**Comment by NoobChengXY** [comment]
也不修改启动脚本，就只有.cubewhy不存在时生成一次

**Comment by NoobChengXY** [comment]
还有脚本中的JavaAgent参数没加双引号

**Comment by CubeWhy** [comment]
我这边会读取配置文件，主播是不是把javaagent扔到mods里边了

**Comment by NoobChengXY** [comment]
不是，他默认是LC-CN那里的javaagent，然后我把LC-CN扔Program Files里，路径中有空格

**Comment by NoobChengXY** [comment]
LC需要管理员权限吗？我怀疑是权限不够

**Comment by NoobChengXY** [comment]
那个offline脚本是干嘛用的？

**Comment by CubeWhy** [comment]
用来调试mod用的

**Comment by NoobChengXY** [comment]
所以，LC-CN要不要管理员权限？

**Comment by CubeWhy** [comment]
不需要

**Comment by CubeWhy** [comment]
> 不是，他默认是LC-CN那里的javaagent，然后我把LC-CN扔Program Files里，路径中有空格

没有让你扔到Program Files里，帮助文档写了

**Comment by CubeWhy** [comment]
该问题确实存在，下个版本会进行修复
感谢反馈

**Comment by WenShao233** [comment]
Are you OK?
修好了吗？

**Comment by CubeWhy** [comment]
修复了之后此议题会关闭
由于开发重点在LiquidLunar上面，lunarcn开发会被推迟

**Comment by CubeWhy** [comment]
> Are you OK? 修好了吗？

今天又看了遍代码，并没有该问题，之前想乱了
